### ISSUE TITLE
QuPath 0.2.3 Extension loading error

### ISSUE THREAD

**Issue by snibbor** [savmasse/qupath-extension-tunel#3]
Hi Sam,

I was wondering if you could help me troubleshoot this error to get this plugin to work and if I could modify it for a similar task.

The error I am receiving is this.

`ERROR: Error loading extension qupath.lib.DL4JExtension@3fcafaea: 'void qupath.lib.gui.QuPathGUI.addImageDataChangeListener(qupath.lib.gui.ImageDataChangeListener)'
    at qupath.lib.TestCommand.<init>(TestCommand.java:119)
    at qupath.lib.DL4JExtension.installExtension(DL4JExtension.java:18)
    at qupath.lib.gui.QuPathGUI.refreshExtensions(QuPathGUI.java:1578)
    at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:1059)
    at qupath.lib.gui.QuPathApp.start(QuPathApp.java:60)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)
ERROR: It is recommended that you delete file:/D:/Programs/QuPath-0.2.3/extensions/qupath-extension-dl4j.jar and restart QuPath
INFO: Loaded extension Experimental extension (2 ms)
INFO: Loaded extension ImageJ extension (45 ms)
INFO: Loaded extension JPen extension (18 ms)
INFO: Loaded extension Processing extension (25 ms)
INFO: Loaded extension Rich script editor extension (257 ms)
INFO: Loaded extension SVG export extension (1 ms)
ERROR: Error loading extension qupath.lib.scripting.ThesisExtension@31264672: 'qupath.lib.objects.classes.PathClass qupath.lib.objects.classes.PathClassFactory.getPathClass(java.lang.String)'
    at qupath.lib.scripting.ThesisExtension.installExtension(ThesisExtension.java:33)
    at qupath.lib.gui.QuPathGUI.refreshExtensions(QuPathGUI.java:1578)
    at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:1059)
    at qupath.lib.gui.QuPathApp.start(QuPathApp.java:60)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)
ERROR: It is recommended that you delete file:/D:/Programs/QuPath-0.2.3/extensions/qupath-extension-tunel.jar and restart QuPath`

Thank you for your help.

**Comment by savmasse** [comment]
Hi Charles,

Thank you for your interest in this extension! 

This is an old project that has not been updated for the latest version of QuPath. The extension was developed for QuPath v0.1.1 (v0.1.2 should work as well). I have not kept up with QuPath development so I don't know which changes were made that would cause the extensions to no longer work.

If you don't require any of the QuPath functionality that has been added since 0.1.2 then you could simply download this old version from https://github.com/qupath/qupath/releases/tag/v0.1.2 and the plugin should work as described in the README file.

If you do need the latest version of QuPath for your project then I would recommend that you build your own plugin, because updating/fixing mine for the new version may be more trouble than to just write it anew from scratch.

Definitely let me know if you have still have questions.

Best regards,
Sam
